### ISSUE TITLE
How can I add cpu quota for the process?

### ISSUE THREAD

**Issue by phenrigomes** [Shopify/ess#20]
I saw that the sandbox can be executed with memory, time and instructions quotas. But and about cpu quotas, cant a code run 100% of cpu?

**Comment by clayton-shopify** [comment]
There is no way to limit CPU utilization. Only execution time and VM instructions can be limited.

**Comment by phenrigomes** [comment]
I tried to use this library passing a ruby object for the sandbox, but I
could not do this. I could pass a object via dict, but a complete instance
like shopify objects not.

2017-08-01 13:04 GMT-03:00 Clayton Smith <notifications@github.com>:
