### ISSUE TITLE
ESS architecture

### ISSUE THREAD

**Issue by nwmcsween** [Shopify/ess#27]
I glanced over ESS and wondered why it was built the way it is. The code in /ext seems to be relatively simple and could be reimplemented with [s6](https://skarnet.org/software) et al and a cli wrapper for [kafel](https://github.com/google/kafel) (nsjail is too broad) for seccomp filtering. A sandboxed app could use (execline)[https://skarnet.org/software/execline] and would be something like:
````
#!/bin/execlineb -P
# Memory and cpu time hard limits
s6-softlimit opts
nsjail --seccomp-string "allowed syscalls"
mrubybin
````

If there needs to be an API of sorts you could pass ENV vars via `importas` for setting different limits, etc.

Is there anything I'm missing?

**Comment by alexsnaps** [comment]
Right, there are multiple approaches to addressing any given problem. It's always a matter of trader offs. ESS is the concretization of what was the most useful approach based on _our_ needs... But it might indeed not be the best for you… Choices :)
I don't see how (thinking about it quickly) how these very same goals could have been easily implemented with your alternative but, as you say "the code is relatively simple" so it didn't feel like a too crazy approach. Most importantly kafel wasn't even a thing when we rolled this out (this is the OSS repository, there has been more work done on this internally _before_ releasing it to the wider public).
Hope this makes _some_ sense!
