### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by jasl** [Shopify/ess#29]
Hi, thank for the awesome work!

I found the license in `gemspec` is `Proprietary`, but there also has a MIT license in root directory, which is the right license that ESS using? May I fork it and build my own gems?

**Comment by alexsnaps** [comment]
Yeah… sorry, it's an oversight. It all started as `Proprietary` internally and we then took a pass a cleaning things up & open sourcing… under the MIT license.

**Comment by jasl** [comment]
Thank you for clarify this!
